### ISSUE TITLE
Propagate "query" URL parameter when clicking "to full protocol"

### ISSUE THREAD

**Issue by SgtTepper** [SgtTepper/BetaKnessetWeb#17]
The query which highlights text in the full protocol view is missing,
it needs to be propagated from the originating page so it would highlight the same text in the full document view.

should look like this after fixed:
![image](https://user-images.githubusercontent.com/27574684/111121180-ff3fbd80-8574-11eb-9181-08f13457b972.png)

**Comment by yoavshati** [comment]
Just tried it and it looks like the bug has been fixed at some point

**Comment by thebne** [comment]
@yoavshati  right, thanks.

if you want to help with something simple, https://github.com/SgtTepper/BetaKnessetWeb/tree/feature/timeline is just waiting for tabs (between timeline and word cloud view).
