### ISSUE TITLE
Clear query on error (or support retrying manually)

### ISSUE THREAD

**Issue by thebne** [SgtTepper/BetaKnessetWeb#19]
whenever there's an error with the request, the query stays but the user can't search again (it knows there's a result already so it doesn't run it).

**Comment by idannik** [comment]
Hi, 
Is this still relevant? I could not reproduce this bug.
Do you have an example of what query can show this bug?

I tried the following query, but was able to run another query afterwards (for example "ביבי" )
![image](https://user-images.githubusercontent.com/9072104/181899350-8d8a3d93-4e5b-432c-b383-490a153cb5a3.png)

**Comment by thebne** [comment]
@idannik 
when this happens, the query field should clean - the state is saved as "searched and returned with results" somewhere (I assume), so consecutive searches fail. Did you try to search again after seeing this message?

**Comment by idannik** [comment]
> @idannik when this happens, the query field should clean - the state is saved as "searched and returned with results" somewhere (I assume), so consecutive searches fail. Did you try to search again after seeing this message?

I tried to search again and it seemed to work fine.
The error of the previous failed query is not showing.

**Comment by thebne** [comment]
> > @idannik when this happens, the query field should clean - the state is saved as "searched and returned with results" somewhere (I assume), so consecutive searches fail. Did you try to search again after seeing this message?
> 
> I tried to search again and it seemed to work fine. The error of the previous failed query is not showing.

When I experienced it, it wasn't the error that's staying but the quote prompt.

I will try to reproduce it and add more info. Thanks
